# Generated by Django 3.1.3 on 2022-08-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile/photos'),
        ),
    ]
